name: rev2agent-part-test
version: "0.1"
summary: Revtwo agent snap part test
description: Revtwo agent snap part test for remote support of linux devices

confinement: devmode
#confinement: strict
#confinement: classic
#grade: stable
grade: devel

apps:
  rev2agent:
    plugs: [network-bind, home]
    command: run-rev2agent
    daemon: simple
    
parts:
#replace rev2agent-part-test with your part
  rev2agent-part-test:
    plugin: dump
    source: .
  rev2agent:
    after: [rev2agent-part-test]
    organize:
      configure: snap/hooks/configure


