name: rev2agent
version: "0.1"
summary: Revtwo agent snap part test
description: Revtwo agent snap part test for remote support of linux devices

confinement: devmode
#confinement: strict
#confinement: classic
#grade: stable
grade: devel

apps:
#  rev2agent-part-test:
#    command: run-hello-sample
  rev2agent:
    plugs: [network-bind, home]
    command: run-rev2agent
#    command: run-hello-sample
    daemon: simple
    
parts:
#replace rev2agent-part-test with your part
  rev2agent:
    organize:
      configure: snap/hooks/configure


